# Generated by Django 5.1.4 on 2024-12-09 14:56

import clients.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_address_alter_client_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['client'], 'verbose_name': 'Teléfono', 'verbose_name_plural': 'Teléfonos'},
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombres y apellido'),
        ),
        migrations.AlterField(
            model_name='client',
            name='refer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client', validators=[clients.models.non_empty_field_warning], verbose_name='Referido por'),
        ),
    ]
