# Generated by Django 5.1.4 on 2024-12-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_options_alter_phone_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='client',
            name='refer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referido por'),
        ),
    ]
